# App-specific tweaks
source = ~/.config/hypr/hyprland/apps/browser.conf
source = ~/.config/hypr/hyprland/apps/system.conf
source = ~/.config/hypr/hyprland/apps/terminals.conf
#source = ~/.config//omarchy/default/hypr/apps/hyprshot.conf
#source = ~/.config//omarchy/default/hypr/apps/steam.conf
#source = ~/.config//omarchy/default/hypr/apps/geforce.conf
#source = ~/.config//omarchy/default/hypr/apps/moonlight.conf
#source = ~/.config//omarchy/default/hypr/apps/system.conf
#source = ~/.config//omarchy/default/hypr/apps/terminals.conf
#source = ~/.config//omarchy/default/hypr/apps/walker.conf

