#################
### AUTOSTART ###
#################

exec-once = uwsm-app -- mako
exec-once = uwsm-app -- waybar
exec-once = uwsm-app -- fcitx5 --disable notificationitem
exec-once = uwsm-app -- swaybg -i ~/.config/prometheus/current/background -m fill
exec-once = uwsm-app -- swayosd-server
exec-once = systemctl --user import-enviroment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-enviroment --systemd --all
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
