###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = yazi
#$menu = rofi -show drun
$menu = prometheus-menu
$appMenu = prometheus-launch-walker
$browser = brave
$musicPlayer = spotify
