###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = yazi
$appMenu = rofi -show drun
$menu = prometheus-menu
$browser = brave
$musicPlayer = spotify-launcher
$notes = obsidian -disable-gpu
