bash $PROMETHEUS_INSTALL/config/config.sh
bash $PROMETHEUS_INSTALL/config/theme.sh
bash $PROMETHEUS_INSTALL/config/branding.sh
bash $PROMETHEUS_INSTALL/config/git.sh
bash $PROMETHEUS_INSTALL/config/gpg.sh
bash $PROMETHEUS_INSTALL/config/increase-file-watchers.sh
bash $PROMETHEUS_INSTALL/config/docker.sh
bash $PROMETHEUS_INSTALL/config/mimetypes.sh
bash $PROMETHEUS_INSTALL/config/localdb.sh 
bash $PROMETHEUS_INSTALL/config/walker-elephant.sh 
bash $PROMETHEUS_INSTALL/config/fast-shutdown.sh 
bash $PROMETHEUS_INSTALL/config/unmount-fuse.sh 
bash $PROMETHEUS_INSTALL/config/input-group.sh 
bash $PROMETHEUS_INSTALL/config/powerprofilesctl-rules.sh 
bash $PROMETHEUS_INSTALL/config/wifi-powersave-rules.sh 
bash $PROMETHEUS_INSTALL/config/plocate-ac-only.sh 
bash $PROMETHEUS_INSTALL/config/hardware/network.sh 
bash $PROMETHEUS_INSTALL/config/hardware/set-wireless-regdom.sh 
bash $PROMETHEUS_INSTALL/config/hardware/bluetooth.sh 
bash $PROMETHEUS_INSTALL/config/hardware/printer.sh 
bash $PROMETHEUS_INSTALL/config/hardware/nvidia.sh 
bash $PROMETHEUS_INSTALL/config/hardware/vulkan.sh 
