include ~/.config/prometheus/current/theme/kitty.conf

# Font
bold_italic_font auto
font_size        9.0

# Window
window_padding_width 6
hide_window_decorations yes
confirm_os_window_close 0

# Aesthetics
shell_integration no-cursor
enable_audio_bell no

